V1.1
* feat: add restaurant distance calculation service - App V1.0

feat: all test pass

feat: add addressRepo Tests, more refactor

feat: refactor almost everything to use Address object instead of AddressDTO

feat: refactor seller restaurant add

feat: refactor delivery domain and tests

feat: adapt controllers for ip usage instead of address

feat: add abstractapi.com_geolocation_1.0.0_openapi.json configuration for address fetching

feat: add simple rest api, fix: restaurant Add, order Add

feat: refactored all tests, all pass

feat: make views more consistent with the model, add simple validation

fix: some fixes from manual testing

feat: add order Data IT tests, fix: impl, TDD for the top I guess

feat: add restaurant management crud test, fix: psql container configuration with flyway

feat: add Order Checkbox controller

fix: for some reason hiddenmethod filters for DELETE and PATCH etc do not work no matter what I configure. decided to use @PostMapping instead

fix: fix again

fix: malformed multi requestParam requests

feat: view has already been adapted huh

feat: add order management IT, view refactor needed

feat: add restaurant management Controller IT

feat: refactor controllers for easier test use

fix: turns out you count pages from 0

fix: repaired all links I left broken for some reason

feat: add restaurant repo impl

feat: add address to restaurant fix: pageNumbers were not properly implemented

feat: add address to restaurant

feat: add order address and restaurant fields

feat: refine restaurant service impl

feat: add order services impl, order domain impl, move password hashing to service layer

feat: add entity relations

fix: more fixes, all works now, it's basically impossible to code using TDD with constantly changing code like that, I suppose I should have created a more strict plan

feat: refactor seller and client id search to use a service instead of passing variables.

feat: add post and delete restaurantManagement controllers impl

fix: go back links needed additional values, fix: ACCOUNT role not properly registered for admin - caused security loop memory errors, feat: order controller impl

feat: add discovery restaurant controller pagination support - if works unknown

feat: controller parameter naming refactor

feat: add views and orderController template

fix: never use @NotNull and @NotEmpty Together

error: unexpected out of memory error

feat: add accountManagement implementation - admin functions still needed

feat: add simple accountManagement template.

feat: add basic securityConfig, debug level configuration, fix: update security Version to remove a configuration bug, fix logback configuration, caused by copy paste.

feat: restored previous tests for future refactor

feat: added crudServices Impl, won't unit test them, it's just redeclaration

fix: turns out my tests weren't included in the component scan range of ApplicationRunner, all works now, I coded the service layer so no point in reversing it.

fix: turns out @SpringMvc Tests don't allow using @Repository Components, I think. Relaxed architecture is not available then. feat: add RestaurantManagement Services, change crudProvider in controller.

fix: delete unit Controller tests - mockito doesnt like multiple class injections

feat: add Mappers

feat: add OrderEntity, DefaultController configuration, default html templates

feat: add test configuration

feat: add database table structure fix, add restaurant controller tests: spring bean component configuration, controller view paths,

feat: add get restaurantManagement controllers

feat: add mappers

feat: add bare-bones domain objects

feat: after some more architecture refactoring and reflection, add service functions

feat: add init project design

* feat: add more account management functions

* feat: image functionalities attempt 1

* feat: added image functions, tests needed

* feat: refine seller order view

* feat: refactor tests, account test fails, minor error adjustments

* feat: some api testing, why does hamcrest escapes " characters, why a JSONArray doesn't maintain the correct order... I guess @WebMvcTest is not the right way for this

* feat: finish tests, refine rest api - Slf4j warning appears - idk how to fix it

* feat: add jacoco

* feat: tried to add wiremock stub for ip api, unfortunately it didn't work, probably because of api returning "mono"

* feat: refine validation and controllers, add address saving after api fetch

* feat: refactor curl commands

* feat: final adjustments

* feat: diagrams